version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    env_file:
      - .env
    depends_on:
      - db
    entrypoint: ['/app/startup.sh']

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: adonis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myDatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
